# Just some tests of make4ht call

extensions:
	make4ht -f html5+tidy simple-example.tex

staticsite:
	make4ht -m publish simple-example.tex

build:
	make4ht -ulm draft -e mybuild.mk4 joincharacters.tex
